- name: installing  Apache on amz Linux hosts
  hosts : EC2_clients
  tasks : 
    - name: update all the software packages
      yum:
        name: '*'
        state: latest
    - name: Install the latest version of Apache
      yum:
        name: httpd
        state: latest
    - name: Start service Apache 
      ansible.builtin.service:
        name: httpd
        state: started
    - name: Enable service httpd, and not touch the state
      ansible.builtin.service:
        name: httpd
        enabled: yes
    - name: Copy index.html file from controller to the clients 
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/
- name : this play will display messages on all ubunt clients
  hosts : ubuntu_clients 
  tasks:
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: "This is my first try for the playbook on ansible"
    - name: ping all ubuntu clients
      ansible.builtin.ping:
            


